### ISSUE TITLE
Unable to find `v1` tag error in Github Actions

### ISSUE THREAD

**Issue by Justintime50** [thebritican/fetch-latest-release#8]
If you try using this action on Github Actions, you're met with the following:

```
Error: Unable to resolve action `thebritican/fetch-latest-release@v1`, unable to find version `v1`
```

We should update the tags to point to v2 as it's the most recent one and update the documentation to reflect that as well.

**Comment by MostefaKamalLala** [comment]
v2.0.0 actually

**Comment by Justintime50** [comment]
Clearly not a priority. Closing.
